server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://wang:7001/eureka/ #,http://xiang:7002/eureka/
  instance:
    instance-id: order8080
spring:
  application:
    name: cloud-order-service
