server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: api-payment
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
            #- After=2020-05-27T23:40:08.433+08:00[Asia/Shanghai]
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://wang:7001/eureka/  #,http://xiang:7002/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2
  instance:
    instance-id: gateway9527
    prefer-ip-address: true






